var div1=document.createElement("div")
var text=document.createTextNode("Login Page")
var input=document.createElement("input")
var button1=document.createElement("button")
var buttontext=document.createTextNode("click")
button1.appendChild(buttontext)
div1.appendChild(text)
div1.appendChild(input)
 div1.appendChild(button1)
document.body.appendChild(div1)